defaults:
  crypto_envelope: acrablock

schemas:
  - table: test
    columns:
      - id
      - data_str
      - masking
      - token_i32
      - data_i32
      - token_i64
      - data_i64
      - token_str
      - token_bytes
      - token_email
    encrypted:
      - column: data_str
        data_type: "str"
      - column: masking
        masking: "xxxx"
        plaintext_length: 3
        plaintext_side: "left"
        data_type: "str"
      - column: token_i32
        token_type: int32
        tokenized: true
      - column: data_i32
        data_type: "int32"
      - column: token_i64
        token_type: int64
        tokenized: true
      - column: data_i64
        data_type: "int64"
      - column: token_bytes
        token_type: bytes
        tokenized: true
      - column: token_str
        token_type: str
        tokenized: true
      - column: token_email
        token_type: email
        tokenized: true

  - table: users
    columns:
      - id
      - email
    encrypted:
      - column: email