schemas:
  # used in test.py
  - table: films
    columns:
      - code
      - title
      - kind
    encrypted:
      - column: kind
        searchable: true
        searchable_prefix: 3



#schemas:
#  # used in test.py
#  - table: test_type_aware_decryption_with_defaults
#    columns:
#      - id
#      - value_str
#      - value_bytes
#      - value_int32
#      - value_int64
#      - value_null_str
#      - value_null_int32
#      - value_empty_str
#
#    encrypted:
#      - column: value_str
#        token_type: int64
#        data_type_db_identifier: 1043
#        response_on_fail: default_value
#        default_data_value: "value_str"
#
#      - column: value_bytes
#        data_type_db_identifier: 17
#        response_on_fail: default_value
#        default_data_value: "dmFsdWVfYnl0ZXM="
#
#      - column: value_int32
#        data_type_db_identifier: 23
#        response_on_fail: default_value
#        default_data_value: "32"
#
#      - column: value_int64
#        data_type_db_identifier: 20
#        response_on_fail: default_value
#        default_data_value: "64"
#
#      - column: value_null_str
#        data_type_db_identifier: 1043
#
#      - column: value_null_int32
#        data_type_db_identifier: 1043
#
#      - column: value_empty_str
#        data_type_db_identifier: 25






