source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
project 'AcraWriterUsage.xcodeproj'
inhibit_all_warnings!
use_frameworks!

target :"AcraWriterUsage" do
	pod 'acrawriter'
end


target "AcraWriterUsageTests" do
	pod 'acrawriter'
end
