# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import api_pb2 as api__pb2


class ReaderStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Decrypt = channel.unary_unary(
        '/grpc_api.Reader/Decrypt',
        request_serializer=api__pb2.DecryptRequest.SerializeToString,
        response_deserializer=api__pb2.DecryptResponse.FromString,
        )


class ReaderServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Decrypt(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ReaderServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Decrypt': grpc.unary_unary_rpc_method_handler(
          servicer.Decrypt,
          request_deserializer=api__pb2.DecryptRequest.FromString,
          response_serializer=api__pb2.DecryptResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'grpc_api.Reader', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
