version: "2"

services:
  pg:
    image: postgres
    ports:
      - "5432:5432"

  acraserver:
    image: cossacklabs/acraserver
    depends_on:
      - pg
    links:
      - pg:postgresql_link

    volumes:
      - ../.acrakeys:/keys

    command: ["--zonemode"]

  acraproxy:
    image: cossacklabs/acraproxy
    depends_on:
      - acraserver
    ports:
      - "9494:9494"
      - "9191:9191"
    links:
      - acraserver:acraserver_link
    volumes:
      - ../.acrakeys:/keys

    command: ["--client_id=client", "--enable_http_api"]
