// Code generated by protoc-gen-go.
// source: cmd/acra-reader/grpc_api/api.proto
// DO NOT EDIT!

/*
Package grpc_api is a generated protocol buffer package.

It is generated from these files:
	cmd/acra-reader/grpc_api/api.proto

It has these top-level messages:
	DecryptRequest
	DecryptResponse
*/
package grpc_api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DecryptRequest struct {
	ClientId   []byte `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ZoneId     []byte `protobuf:"bytes,2,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	Acrastruct []byte `protobuf:"bytes,3,opt,name=acrastruct,proto3" json:"acrastruct,omitempty"`
}

func (m *DecryptRequest) Reset()                    { *m = DecryptRequest{} }
func (m *DecryptRequest) String() string            { return proto.CompactTextString(m) }
func (*DecryptRequest) ProtoMessage()               {}
func (*DecryptRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type DecryptResponse struct {
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *DecryptResponse) Reset()                    { *m = DecryptResponse{} }
func (m *DecryptResponse) String() string            { return proto.CompactTextString(m) }
func (*DecryptResponse) ProtoMessage()               {}
func (*DecryptResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*DecryptRequest)(nil), "grpc_api.DecryptRequest")
	proto.RegisterType((*DecryptResponse)(nil), "grpc_api.DecryptResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Reader service

type ReaderClient interface {
	Decrypt(ctx context.Context, in *DecryptRequest, opts ...grpc.CallOption) (*DecryptResponse, error)
}

type readerClient struct {
	cc *grpc.ClientConn
}

func NewReaderClient(cc *grpc.ClientConn) ReaderClient {
	return &readerClient{cc}
}

func (c *readerClient) Decrypt(ctx context.Context, in *DecryptRequest, opts ...grpc.CallOption) (*DecryptResponse, error) {
	out := new(DecryptResponse)
	err := grpc.Invoke(ctx, "/grpc_api.Reader/Decrypt", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Reader service

type ReaderServer interface {
	Decrypt(context.Context, *DecryptRequest) (*DecryptResponse, error)
}

func RegisterReaderServer(s *grpc.Server, srv ReaderServer) {
	s.RegisterService(&_Reader_serviceDesc, srv)
}

func _Reader_Decrypt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecryptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReaderServer).Decrypt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_api.Reader/Decrypt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReaderServer).Decrypt(ctx, req.(*DecryptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Reader_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc_api.Reader",
	HandlerType: (*ReaderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Decrypt",
			Handler:    _Reader_Decrypt_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("cmd/acra-reader/grpc_api/api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 199 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x52, 0x4a, 0xce, 0x4d, 0xd1,
	0x4f, 0x4c, 0x2e, 0x4a, 0xd4, 0x2d, 0x4a, 0x4d, 0x4c, 0x49, 0x2d, 0xd2, 0x4f, 0x2f, 0x2a, 0x48,
	0x8e, 0x4f, 0x2c, 0xc8, 0xd4, 0x07, 0x62, 0xbd, 0x82, 0xa2, 0xfc, 0x92, 0x7c, 0x21, 0x0e, 0x98,
	0x98, 0x52, 0x1a, 0x17, 0x9f, 0x4b, 0x6a, 0x72, 0x51, 0x65, 0x41, 0x49, 0x50, 0x6a, 0x61, 0x69,
	0x6a, 0x71, 0x89, 0x90, 0x34, 0x17, 0x67, 0x72, 0x4e, 0x66, 0x6a, 0x5e, 0x49, 0x7c, 0x66, 0x8a,
	0x04, 0xa3, 0x02, 0xa3, 0x06, 0x4f, 0x10, 0x07, 0x44, 0xc0, 0x33, 0x45, 0x48, 0x9c, 0x8b, 0xbd,
	0x2a, 0x3f, 0x2f, 0x15, 0x24, 0xc5, 0x04, 0x96, 0x62, 0x03, 0x71, 0x81, 0x12, 0x72, 0x5c, 0x5c,
	0x20, 0x3b, 0x8b, 0x4b, 0x8a, 0x4a, 0x93, 0x4b, 0x24, 0x98, 0xc1, 0x72, 0x48, 0x22, 0x4a, 0xaa,
	0x5c, 0xfc, 0x70, 0x7b, 0x8a, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0x84, 0xb8, 0x58, 0x52, 0x12,
	0x4b, 0x12, 0xa1, 0x76, 0x80, 0xd9, 0x46, 0x5e, 0x5c, 0x6c, 0x41, 0x60, 0x57, 0x0b, 0x39, 0x70,
	0xb1, 0x43, 0x35, 0x08, 0x49, 0xe8, 0xc1, 0x9c, 0xab, 0x87, 0xea, 0x56, 0x29, 0x49, 0x2c, 0x32,
	0x10, 0xd3, 0x95, 0x18, 0x92, 0xd8, 0xc0, 0x7e, 0x35, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x60,
	0x6d, 0x48, 0x25, 0x11, 0x01, 0x00, 0x00,
}
