package cmd

const (
	DEFAULT_PROXY_PORT                = 9494
	DEFAULT_PROXY_API_PORT            = 9191
	DEFAULT_PROXY_CONNECTION_PROTOCOL = "tcp"
	DEFAULT_PROXY_HOST                = "127.0.0.1"
	DEFAULT_ACRA_HOST                 = "0.0.0.0"
	DEFAULT_ACRA_PORT                 = 9393
	DEFAULT_ACRA_API_PORT             = 9090
	DEFAULT_ACRA_CONNECTION_PROTOCOL  = "tcp"
	DEFAULT_ACRA_CONFIGUI_HOST        = "127.0.0.1"
	DEFAULT_ACRA_CONFIGUI_PORT        = 8000
	DEFAULT_ACRA_CONFIGUI_STATIC      = "cmd/acra_configui/static"
)
