package cmd

const (
	DEFAULT_CONNECTOR_PORT                = 9494
	DEFAULT_CONNECTOR_API_PORT            = 9191
	DEFAULT_CONNECTOR_CONNECTION_PROTOCOL = "tcp"
	DEFAULT_CONNECTOR_HOST                = "127.0.0.1"
	DEFAULT_ACRA_HOST                     = "0.0.0.0"
	DEFAULT_ACRA_PORT                     = 9393
	DEFAULT_ACRA_API_PORT                 = 9090
	DEFAULT_ACRA_AUTH_PATH                = "configs/auth.keys"
	DEFAULT_ACRA_CONNECTION_PROTOCOL      = "tcp"
	DEFAULT_ACRA_CONFIGUI_HOST            = "127.0.0.1"
	DEFAULT_ACRA_CONFIGUI_PORT            = 8000
	DEFAULT_ACRA_CONFIGUI_STATIC          = "cmd/acra_configui/static"
	DEFAULT_ACRA_CONFIGUI_AUTH_MODE       = "auth_on"
	ACRA_CONFIGUI_AUTH_ARGON2_LENGTH      = 32
	ACRA_CONFIGUI_AUTH_ARGON2_MEMORY      = 8 * 1024
	ACRA_CONFIGUI_AUTH_ARGON2_TIME        = 3
	ACRA_CONFIGUI_AUTH_ARGON2_THREADS     = 2
)
