version: 0.91.0
# Client ID should be name of file with private key
client_id: 

# path to config
config_file: 

# Connection string for db
connection_string: 

# dump config
dump_config: false

# Escape bytea format
escape: false

# Execute inserts
execute: false

# Generate with yaml config markdown text file with descriptions of all args
generate_markdown_args_table: false

# Query for insert decrypted data with placeholders (pg: $n, mysql: ?)
insert: 

# Folder from which the keys will be loaded
keys_dir: .acrakeys

# Handle MySQL connections
mysql_enable: false

# File for store inserts queries
output_file: decrypted.sql

# Handle Postgresql connections
postgresql_enable: false

# Query to fetch data for decryption
select: 

# Connection string (http://x.x.x.x:yyyy) for loading ACRA_MASTER_KEY from HashiCorp Vault
vault_connection_api_string: 

# KV Secret Path (secret/) for reading ACRA_MASTER_KEY from HashiCorp Vault
vault_secrets_path: secret/

# Path to CA certificate for HashiCorp Vault certificate validation
vault_tls_ca_path: 

# Path to client TLS certificate for reading ACRA_MASTER_KEY from HashiCorp Vault
vault_tls_client_cert: 

# Path to private key of the client TLS certificate for reading ACRA_MASTER_KEY from HashiCorp Vault
vault_tls_client_key: 

# Use TLS to encrypt transport with HashiCorp Vault
vault_tls_transport_enable: false

# Turn on zone mode
zonemode_enable: false

