version: 0.94.0
# Client ID should be name of file with private key
client_id: 

# path to config
config_file: 

# Connection string for db
connection_string: 

# dump config
dump_config: false

# Escape bytea format
escape: false

# Execute inserts
execute: false

# Generate with yaml config markdown text file with descriptions of all args
generate_markdown_args_table: false

# Query for insert decrypted data with placeholders (pg: $n, mysql: ?)
insert: 

# Folder from which the keys will be loaded
keys_dir: .acrakeys

# Keystore encryptor strategy: <env_master_key|kms_encrypted_master_key|vault_master_key|kms_per_client
keystore_encryption_type: env_master_key

# KMS credentials JSON file path
kms_credentials_path: 

# KMS type for using: <aws>
kms_type: 

# Handle MySQL connections
mysql_enable: false

# File for store inserts queries
output_file: decrypted.sql

# Handle Postgresql connections
postgresql_enable: false

# Query to fetch data for decryption
select: 

# Connection string (http://x.x.x.x:yyyy) for loading ACRA_MASTER_KEY from HashiCorp Vault
vault_connection_api_string: 

# KV Secret Path (secret/) for reading ACRA_MASTER_KEY from HashiCorp Vault
vault_secrets_path: secret/

# Path to CA certificate for HashiCorp Vault certificate validation (deprecated since 0.94.0, use `vault_tls_client_ca`)
vault_tls_ca_path: 

# Set authentication mode that will be used in TLS connection. Values in range 0-4 that set auth type (https://golang.org/pkg/crypto/tls/#ClientAuthType). Default is -1 which means NotSpecified and will be used value from tls_auth.
vault_tls_client_auth: -1

# Path to root certificate which will be used with system root certificates to validate peer's certificate. Uses --tls_ca value if not specified.
vault_tls_client_ca: 

# Path to certificate. Uses --tls_cert value if not specified.
vault_tls_client_cert: 

# Path to private key that will be used for TLS connections. Uses --tls_key value if not specified.
vault_tls_client_key: 

# Expected Server Name (SNI) from the service's side.
vault_tls_client_sni: 

# How many CRLs to cache in memory (use 0 to disable caching)
vault_tls_crl_client_cache_size: 16

# How long to keep CRLs cached, in seconds (use 0 to disable caching, maximum: 300 s)
vault_tls_crl_client_cache_time: 0

# Put 'true' to check only final/last certificate, or 'false' to check the whole certificate chain using CRL
vault_tls_crl_client_check_only_leaf_certificate: false

# How to treat CRL URL described in certificate itself: <use|trust|prefer|ignore>
vault_tls_crl_client_from_cert: prefer

# URL of the Certificate Revocation List (CRL) to use
vault_tls_crl_client_url: 

# Put 'true' to check only final/last certificate, or 'false' to check the whole certificate chain using OCSP
vault_tls_ocsp_client_check_only_leaf_certificate: false

# How to treat OCSP server described in certificate itself: <use|trust|prefer|ignore>
vault_tls_ocsp_client_from_cert: prefer

# How to treat certificates unknown to OCSP: <denyUnknown|allowUnknown|requireGood>
vault_tls_ocsp_client_required: denyUnknown

# OCSP service URL
vault_tls_ocsp_client_url: 

# Use TLS to encrypt transport with HashiCorp Vault
vault_tls_transport_enable: false

