handlers:
  - handler: blacklist
    queries:
      - INSERT INTO SalesStaff1 VALUES (1, 'Stephen', 'Jiang');
      - SELECT AVG(Price) FROM Products;
    tables:
      - EMPLOYEE_TBL
      - Customers
    rules:
      - SELECT * FROM EMPLOYEE WHERE CITY='Seattle';

  - handler: whitelist
    queries:
    tables:
      - EMPLOYEE
    rules: