# Create keypair for AcraConnector only
acra-connector: false

# Create keypair for AcraServer only
acra-server: false

# Create symmetric key for AcraWebconfig's basic auth db
basicauth: false

# Client id
client_id: client

# path to config
config: 

# dump config
dumpconfig: false

# Generate new random master key and save to file
master_key: 

# Folder where will be saved keys
output: .acrakeys

# Folder where will be saved public key
output_public: .acrakeys

# Create keypair for data encryption/decryption
storage: false

