// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: cmd/acra-translator/grpc_api/api.proto

package grpc_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DecryptRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId   []byte `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ZoneId     []byte `protobuf:"bytes,2,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	Acrastruct []byte `protobuf:"bytes,3,opt,name=acrastruct,proto3" json:"acrastruct,omitempty"`
}

func (x *DecryptRequest) Reset() {
	*x = DecryptRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_acra_translator_grpc_api_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DecryptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecryptRequest) ProtoMessage() {}

func (x *DecryptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_acra_translator_grpc_api_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecryptRequest.ProtoReflect.Descriptor instead.
func (*DecryptRequest) Descriptor() ([]byte, []int) {
	return file_cmd_acra_translator_grpc_api_api_proto_rawDescGZIP(), []int{0}
}

func (x *DecryptRequest) GetClientId() []byte {
	if x != nil {
		return x.ClientId
	}
	return nil
}

func (x *DecryptRequest) GetZoneId() []byte {
	if x != nil {
		return x.ZoneId
	}
	return nil
}

func (x *DecryptRequest) GetAcrastruct() []byte {
	if x != nil {
		return x.Acrastruct
	}
	return nil
}

type DecryptResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *DecryptResponse) Reset() {
	*x = DecryptResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_acra_translator_grpc_api_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DecryptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecryptResponse) ProtoMessage() {}

func (x *DecryptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_acra_translator_grpc_api_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecryptResponse.ProtoReflect.Descriptor instead.
func (*DecryptResponse) Descriptor() ([]byte, []int) {
	return file_cmd_acra_translator_grpc_api_api_proto_rawDescGZIP(), []int{1}
}

func (x *DecryptResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type EncryptRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId []byte `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ZoneId   []byte `protobuf:"bytes,2,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	Data     []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *EncryptRequest) Reset() {
	*x = EncryptRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_acra_translator_grpc_api_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EncryptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptRequest) ProtoMessage() {}

func (x *EncryptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_acra_translator_grpc_api_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptRequest.ProtoReflect.Descriptor instead.
func (*EncryptRequest) Descriptor() ([]byte, []int) {
	return file_cmd_acra_translator_grpc_api_api_proto_rawDescGZIP(), []int{2}
}

func (x *EncryptRequest) GetClientId() []byte {
	if x != nil {
		return x.ClientId
	}
	return nil
}

func (x *EncryptRequest) GetZoneId() []byte {
	if x != nil {
		return x.ZoneId
	}
	return nil
}

func (x *EncryptRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type EncryptResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Acrastruct []byte `protobuf:"bytes,1,opt,name=acrastruct,proto3" json:"acrastruct,omitempty"`
}

func (x *EncryptResponse) Reset() {
	*x = EncryptResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_acra_translator_grpc_api_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EncryptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptResponse) ProtoMessage() {}

func (x *EncryptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_acra_translator_grpc_api_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptResponse.ProtoReflect.Descriptor instead.
func (*EncryptResponse) Descriptor() ([]byte, []int) {
	return file_cmd_acra_translator_grpc_api_api_proto_rawDescGZIP(), []int{3}
}

func (x *EncryptResponse) GetAcrastruct() []byte {
	if x != nil {
		return x.Acrastruct
	}
	return nil
}

type TokenizeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId []byte `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ZoneId   []byte `protobuf:"bytes,2,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	// Types that are assignable to Value:
	//	*TokenizeRequest_StrValue
	//	*TokenizeRequest_EmailValue
	//	*TokenizeRequest_Int32Value
	//	*TokenizeRequest_Int64Value
	//	*TokenizeRequest_BytesValue
	Value isTokenizeRequest_Value `protobuf_oneof:"value"`
}

func (x *TokenizeRequest) Reset() {
	*x = TokenizeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_acra_translator_grpc_api_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenizeRequest) ProtoMessage() {}

func (x *TokenizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_acra_translator_grpc_api_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenizeRequest.ProtoReflect.Descriptor instead.
func (*TokenizeRequest) Descriptor() ([]byte, []int) {
	return file_cmd_acra_translator_grpc_api_api_proto_rawDescGZIP(), []int{4}
}

func (x *TokenizeRequest) GetClientId() []byte {
	if x != nil {
		return x.ClientId
	}
	return nil
}

func (x *TokenizeRequest) GetZoneId() []byte {
	if x != nil {
		return x.ZoneId
	}
	return nil
}

func (m *TokenizeRequest) GetValue() isTokenizeRequest_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *TokenizeRequest) GetStrValue() string {
	if x, ok := x.GetValue().(*TokenizeRequest_StrValue); ok {
		return x.StrValue
	}
	return ""
}

func (x *TokenizeRequest) GetEmailValue() string {
	if x, ok := x.GetValue().(*TokenizeRequest_EmailValue); ok {
		return x.EmailValue
	}
	return ""
}

func (x *TokenizeRequest) GetInt32Value() int32 {
	if x, ok := x.GetValue().(*TokenizeRequest_Int32Value); ok {
		return x.Int32Value
	}
	return 0
}

func (x *TokenizeRequest) GetInt64Value() int64 {
	if x, ok := x.GetValue().(*TokenizeRequest_Int64Value); ok {
		return x.Int64Value
	}
	return 0
}

func (x *TokenizeRequest) GetBytesValue() []byte {
	if x, ok := x.GetValue().(*TokenizeRequest_BytesValue); ok {
		return x.BytesValue
	}
	return nil
}

type isTokenizeRequest_Value interface {
	isTokenizeRequest_Value()
}

type TokenizeRequest_StrValue struct {
	StrValue string `protobuf:"bytes,3,opt,name=str_value,json=strValue,proto3,oneof"`
}

type TokenizeRequest_EmailValue struct {
	EmailValue string `protobuf:"bytes,4,opt,name=email_value,json=emailValue,proto3,oneof"`
}

type TokenizeRequest_Int32Value struct {
	Int32Value int32 `protobuf:"varint,5,opt,name=int32_value,json=int32Value,proto3,oneof"`
}

type TokenizeRequest_Int64Value struct {
	Int64Value int64 `protobuf:"varint,6,opt,name=int64_value,json=int64Value,proto3,oneof"`
}

type TokenizeRequest_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,7,opt,name=bytes_value,json=bytesValue,proto3,oneof"`
}

func (*TokenizeRequest_StrValue) isTokenizeRequest_Value() {}

func (*TokenizeRequest_EmailValue) isTokenizeRequest_Value() {}

func (*TokenizeRequest_Int32Value) isTokenizeRequest_Value() {}

func (*TokenizeRequest_Int64Value) isTokenizeRequest_Value() {}

func (*TokenizeRequest_BytesValue) isTokenizeRequest_Value() {}

type TokenizeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//	*TokenizeResponse_StrToken
	//	*TokenizeResponse_EmailToken
	//	*TokenizeResponse_Int32Token
	//	*TokenizeResponse_Int64Token
	//	*TokenizeResponse_BytesToken
	Response isTokenizeResponse_Response `protobuf_oneof:"response"`
}

func (x *TokenizeResponse) Reset() {
	*x = TokenizeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_acra_translator_grpc_api_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenizeResponse) ProtoMessage() {}

func (x *TokenizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_acra_translator_grpc_api_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenizeResponse.ProtoReflect.Descriptor instead.
func (*TokenizeResponse) Descriptor() ([]byte, []int) {
	return file_cmd_acra_translator_grpc_api_api_proto_rawDescGZIP(), []int{5}
}

func (m *TokenizeResponse) GetResponse() isTokenizeResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *TokenizeResponse) GetStrToken() string {
	if x, ok := x.GetResponse().(*TokenizeResponse_StrToken); ok {
		return x.StrToken
	}
	return ""
}

func (x *TokenizeResponse) GetEmailToken() string {
	if x, ok := x.GetResponse().(*TokenizeResponse_EmailToken); ok {
		return x.EmailToken
	}
	return ""
}

func (x *TokenizeResponse) GetInt32Token() int32 {
	if x, ok := x.GetResponse().(*TokenizeResponse_Int32Token); ok {
		return x.Int32Token
	}
	return 0
}

func (x *TokenizeResponse) GetInt64Token() int64 {
	if x, ok := x.GetResponse().(*TokenizeResponse_Int64Token); ok {
		return x.Int64Token
	}
	return 0
}

func (x *TokenizeResponse) GetBytesToken() []byte {
	if x, ok := x.GetResponse().(*TokenizeResponse_BytesToken); ok {
		return x.BytesToken
	}
	return nil
}

type isTokenizeResponse_Response interface {
	isTokenizeResponse_Response()
}

type TokenizeResponse_StrToken struct {
	StrToken string `protobuf:"bytes,1,opt,name=str_token,json=strToken,proto3,oneof"`
}

type TokenizeResponse_EmailToken struct {
	EmailToken string `protobuf:"bytes,2,opt,name=email_token,json=emailToken,proto3,oneof"`
}

type TokenizeResponse_Int32Token struct {
	Int32Token int32 `protobuf:"varint,3,opt,name=int32_token,json=int32Token,proto3,oneof"`
}

type TokenizeResponse_Int64Token struct {
	Int64Token int64 `protobuf:"varint,4,opt,name=int64_token,json=int64Token,proto3,oneof"`
}

type TokenizeResponse_BytesToken struct {
	BytesToken []byte `protobuf:"bytes,5,opt,name=bytes_token,json=bytesToken,proto3,oneof"`
}

func (*TokenizeResponse_StrToken) isTokenizeResponse_Response() {}

func (*TokenizeResponse_EmailToken) isTokenizeResponse_Response() {}

func (*TokenizeResponse_Int32Token) isTokenizeResponse_Response() {}

func (*TokenizeResponse_Int64Token) isTokenizeResponse_Response() {}

func (*TokenizeResponse_BytesToken) isTokenizeResponse_Response() {}

type SearchableEncryptionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId []byte `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ZoneId   []byte `protobuf:"bytes,2,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	Data     []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SearchableEncryptionRequest) Reset() {
	*x = SearchableEncryptionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_acra_translator_grpc_api_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchableEncryptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchableEncryptionRequest) ProtoMessage() {}

func (x *SearchableEncryptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_acra_translator_grpc_api_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchableEncryptionRequest.ProtoReflect.Descriptor instead.
func (*SearchableEncryptionRequest) Descriptor() ([]byte, []int) {
	return file_cmd_acra_translator_grpc_api_api_proto_rawDescGZIP(), []int{6}
}

func (x *SearchableEncryptionRequest) GetClientId() []byte {
	if x != nil {
		return x.ClientId
	}
	return nil
}

func (x *SearchableEncryptionRequest) GetZoneId() []byte {
	if x != nil {
		return x.ZoneId
	}
	return nil
}

func (x *SearchableEncryptionRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SearchableEncryptionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash       []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Acrastruct []byte `protobuf:"bytes,2,opt,name=acrastruct,proto3" json:"acrastruct,omitempty"`
}

func (x *SearchableEncryptionResponse) Reset() {
	*x = SearchableEncryptionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_acra_translator_grpc_api_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchableEncryptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchableEncryptionResponse) ProtoMessage() {}

func (x *SearchableEncryptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_acra_translator_grpc_api_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchableEncryptionResponse.ProtoReflect.Descriptor instead.
func (*SearchableEncryptionResponse) Descriptor() ([]byte, []int) {
	return file_cmd_acra_translator_grpc_api_api_proto_rawDescGZIP(), []int{7}
}

func (x *SearchableEncryptionResponse) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *SearchableEncryptionResponse) GetAcrastruct() []byte {
	if x != nil {
		return x.Acrastruct
	}
	return nil
}

type SearchableDecryptionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId []byte `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ZoneId   []byte `protobuf:"bytes,2,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	Data     []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Hash     []byte `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *SearchableDecryptionRequest) Reset() {
	*x = SearchableDecryptionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_acra_translator_grpc_api_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchableDecryptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchableDecryptionRequest) ProtoMessage() {}

func (x *SearchableDecryptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_acra_translator_grpc_api_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchableDecryptionRequest.ProtoReflect.Descriptor instead.
func (*SearchableDecryptionRequest) Descriptor() ([]byte, []int) {
	return file_cmd_acra_translator_grpc_api_api_proto_rawDescGZIP(), []int{8}
}

func (x *SearchableDecryptionRequest) GetClientId() []byte {
	if x != nil {
		return x.ClientId
	}
	return nil
}

func (x *SearchableDecryptionRequest) GetZoneId() []byte {
	if x != nil {
		return x.ZoneId
	}
	return nil
}

func (x *SearchableDecryptionRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SearchableDecryptionRequest) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type SearchableDecryptionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SearchableDecryptionResponse) Reset() {
	*x = SearchableDecryptionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_acra_translator_grpc_api_api_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchableDecryptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchableDecryptionResponse) ProtoMessage() {}

func (x *SearchableDecryptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_acra_translator_grpc_api_api_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchableDecryptionResponse.ProtoReflect.Descriptor instead.
func (*SearchableDecryptionResponse) Descriptor() ([]byte, []int) {
	return file_cmd_acra_translator_grpc_api_api_proto_rawDescGZIP(), []int{9}
}

func (x *SearchableDecryptionResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SearchableSymEncryptionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId []byte `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ZoneId   []byte `protobuf:"bytes,2,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	Data     []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SearchableSymEncryptionRequest) Reset() {
	*x = SearchableSymEncryptionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_acra_translator_grpc_api_api_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchableSymEncryptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchableSymEncryptionRequest) ProtoMessage() {}

func (x *SearchableSymEncryptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_acra_translator_grpc_api_api_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchableSymEncryptionRequest.ProtoReflect.Descriptor instead.
func (*SearchableSymEncryptionRequest) Descriptor() ([]byte, []int) {
	return file_cmd_acra_translator_grpc_api_api_proto_rawDescGZIP(), []int{10}
}

func (x *SearchableSymEncryptionRequest) GetClientId() []byte {
	if x != nil {
		return x.ClientId
	}
	return nil
}

func (x *SearchableSymEncryptionRequest) GetZoneId() []byte {
	if x != nil {
		return x.ZoneId
	}
	return nil
}

func (x *SearchableSymEncryptionRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SearchableSymEncryptionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash      []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Acrablock []byte `protobuf:"bytes,2,opt,name=acrablock,proto3" json:"acrablock,omitempty"`
}

func (x *SearchableSymEncryptionResponse) Reset() {
	*x = SearchableSymEncryptionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_acra_translator_grpc_api_api_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchableSymEncryptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchableSymEncryptionResponse) ProtoMessage() {}

func (x *SearchableSymEncryptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_acra_translator_grpc_api_api_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchableSymEncryptionResponse.ProtoReflect.Descriptor instead.
func (*SearchableSymEncryptionResponse) Descriptor() ([]byte, []int) {
	return file_cmd_acra_translator_grpc_api_api_proto_rawDescGZIP(), []int{11}
}

func (x *SearchableSymEncryptionResponse) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *SearchableSymEncryptionResponse) GetAcrablock() []byte {
	if x != nil {
		return x.Acrablock
	}
	return nil
}

type SearchableSymDecryptionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId []byte `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ZoneId   []byte `protobuf:"bytes,2,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	Data     []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Hash     []byte `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *SearchableSymDecryptionRequest) Reset() {
	*x = SearchableSymDecryptionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_acra_translator_grpc_api_api_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchableSymDecryptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchableSymDecryptionRequest) ProtoMessage() {}

func (x *SearchableSymDecryptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_acra_translator_grpc_api_api_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchableSymDecryptionRequest.ProtoReflect.Descriptor instead.
func (*SearchableSymDecryptionRequest) Descriptor() ([]byte, []int) {
	return file_cmd_acra_translator_grpc_api_api_proto_rawDescGZIP(), []int{12}
}

func (x *SearchableSymDecryptionRequest) GetClientId() []byte {
	if x != nil {
		return x.ClientId
	}
	return nil
}

func (x *SearchableSymDecryptionRequest) GetZoneId() []byte {
	if x != nil {
		return x.ZoneId
	}
	return nil
}

func (x *SearchableSymDecryptionRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SearchableSymDecryptionRequest) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type SearchableSymDecryptionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SearchableSymDecryptionResponse) Reset() {
	*x = SearchableSymDecryptionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_acra_translator_grpc_api_api_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchableSymDecryptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchableSymDecryptionResponse) ProtoMessage() {}

func (x *SearchableSymDecryptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_acra_translator_grpc_api_api_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchableSymDecryptionResponse.ProtoReflect.Descriptor instead.
func (*SearchableSymDecryptionResponse) Descriptor() ([]byte, []int) {
	return file_cmd_acra_translator_grpc_api_api_proto_rawDescGZIP(), []int{13}
}

func (x *SearchableSymDecryptionResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type QueryHashRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId []byte `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ZoneId   []byte `protobuf:"bytes,2,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	Data     []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *QueryHashRequest) Reset() {
	*x = QueryHashRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_acra_translator_grpc_api_api_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryHashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryHashRequest) ProtoMessage() {}

func (x *QueryHashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_acra_translator_grpc_api_api_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryHashRequest.ProtoReflect.Descriptor instead.
func (*QueryHashRequest) Descriptor() ([]byte, []int) {
	return file_cmd_acra_translator_grpc_api_api_proto_rawDescGZIP(), []int{14}
}

func (x *QueryHashRequest) GetClientId() []byte {
	if x != nil {
		return x.ClientId
	}
	return nil
}

func (x *QueryHashRequest) GetZoneId() []byte {
	if x != nil {
		return x.ZoneId
	}
	return nil
}

func (x *QueryHashRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type QueryHashResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *QueryHashResponse) Reset() {
	*x = QueryHashResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_acra_translator_grpc_api_api_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryHashResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryHashResponse) ProtoMessage() {}

func (x *QueryHashResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_acra_translator_grpc_api_api_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryHashResponse.ProtoReflect.Descriptor instead.
func (*QueryHashResponse) Descriptor() ([]byte, []int) {
	return file_cmd_acra_translator_grpc_api_api_proto_rawDescGZIP(), []int{15}
}

func (x *QueryHashResponse) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type DecryptSymRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId  []byte `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ZoneId    []byte `protobuf:"bytes,2,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	Acrablock []byte `protobuf:"bytes,3,opt,name=acrablock,proto3" json:"acrablock,omitempty"`
}

func (x *DecryptSymRequest) Reset() {
	*x = DecryptSymRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_acra_translator_grpc_api_api_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DecryptSymRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecryptSymRequest) ProtoMessage() {}

func (x *DecryptSymRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_acra_translator_grpc_api_api_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecryptSymRequest.ProtoReflect.Descriptor instead.
func (*DecryptSymRequest) Descriptor() ([]byte, []int) {
	return file_cmd_acra_translator_grpc_api_api_proto_rawDescGZIP(), []int{16}
}

func (x *DecryptSymRequest) GetClientId() []byte {
	if x != nil {
		return x.ClientId
	}
	return nil
}

func (x *DecryptSymRequest) GetZoneId() []byte {
	if x != nil {
		return x.ZoneId
	}
	return nil
}

func (x *DecryptSymRequest) GetAcrablock() []byte {
	if x != nil {
		return x.Acrablock
	}
	return nil
}

type DecryptSymResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *DecryptSymResponse) Reset() {
	*x = DecryptSymResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_acra_translator_grpc_api_api_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DecryptSymResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecryptSymResponse) ProtoMessage() {}

func (x *DecryptSymResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_acra_translator_grpc_api_api_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecryptSymResponse.ProtoReflect.Descriptor instead.
func (*DecryptSymResponse) Descriptor() ([]byte, []int) {
	return file_cmd_acra_translator_grpc_api_api_proto_rawDescGZIP(), []int{17}
}

func (x *DecryptSymResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type EncryptSymRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId []byte `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ZoneId   []byte `protobuf:"bytes,2,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	Data     []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *EncryptSymRequest) Reset() {
	*x = EncryptSymRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_acra_translator_grpc_api_api_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EncryptSymRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptSymRequest) ProtoMessage() {}

func (x *EncryptSymRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_acra_translator_grpc_api_api_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptSymRequest.ProtoReflect.Descriptor instead.
func (*EncryptSymRequest) Descriptor() ([]byte, []int) {
	return file_cmd_acra_translator_grpc_api_api_proto_rawDescGZIP(), []int{18}
}

func (x *EncryptSymRequest) GetClientId() []byte {
	if x != nil {
		return x.ClientId
	}
	return nil
}

func (x *EncryptSymRequest) GetZoneId() []byte {
	if x != nil {
		return x.ZoneId
	}
	return nil
}

func (x *EncryptSymRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type EncryptSymResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Acrablock []byte `protobuf:"bytes,1,opt,name=acrablock,proto3" json:"acrablock,omitempty"`
}

func (x *EncryptSymResponse) Reset() {
	*x = EncryptSymResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_acra_translator_grpc_api_api_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EncryptSymResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptSymResponse) ProtoMessage() {}

func (x *EncryptSymResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_acra_translator_grpc_api_api_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptSymResponse.ProtoReflect.Descriptor instead.
func (*EncryptSymResponse) Descriptor() ([]byte, []int) {
	return file_cmd_acra_translator_grpc_api_api_proto_rawDescGZIP(), []int{19}
}

func (x *EncryptSymResponse) GetAcrablock() []byte {
	if x != nil {
		return x.Acrablock
	}
	return nil
}

var File_cmd_acra_translator_grpc_api_api_proto protoreflect.FileDescriptor

var file_cmd_acra_translator_grpc_api_api_proto_rawDesc = []byte{
	0x0a, 0x26, 0x63, 0x6d, 0x64, 0x2f, 0x61, 0x63, 0x72, 0x61, 0x2d, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x61, 0x70, 0x69, 0x2f, 0x61,
	0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x61,
	0x70, 0x69, 0x22, 0x66, 0x0a, 0x0e, 0x44, 0x65, 0x63, 0x72, 0x79, 0x70, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x12, 0x17, 0x0a, 0x07, 0x7a, 0x6f, 0x6e, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x06, 0x7a, 0x6f, 0x6e, 0x65, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x63,
	0x72, 0x61, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a,
	0x61, 0x63, 0x72, 0x61, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x22, 0x25, 0x0a, 0x0f, 0x44, 0x65,
	0x63, 0x72, 0x79, 0x70, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x22, 0x5a, 0x0a, 0x0e, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64,
	0x12, 0x17, 0x0a, 0x07, 0x7a, 0x6f, 0x6e, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x06, 0x7a, 0x6f, 0x6e, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x31, 0x0a,
	0x0f, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x63, 0x72, 0x61, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x61, 0x63, 0x72, 0x61, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x22, 0xfb, 0x01, 0x0a, 0x0f, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x12, 0x17, 0x0a, 0x07, 0x7a, 0x6f, 0x6e, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x06, 0x7a, 0x6f, 0x6e, 0x65, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x09, 0x73, 0x74,
	0x72, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52,
	0x08, 0x73, 0x74, 0x72, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x21, 0x0a, 0x0b, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x0a, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x21, 0x0a, 0x0b,
	0x69, 0x6e, 0x74, 0x33, 0x32, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x05, 0x48, 0x00, 0x52, 0x0a, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x21, 0x0a, 0x0b, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x0a, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x21, 0x0a, 0x0b, 0x62, 0x79, 0x74, 0x65, 0x73, 0x5f, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x0a, 0x62, 0x79, 0x74, 0x65, 0x73,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0xc9,
	0x01, 0x0a, 0x10, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x09, 0x73, 0x74, 0x72, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x08, 0x73, 0x74, 0x72, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x12, 0x21, 0x0a, 0x0b, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0a, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x21, 0x0a, 0x0b, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x5f, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x0a, 0x69, 0x6e,
	0x74, 0x33, 0x32, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x21, 0x0a, 0x0b, 0x69, 0x6e, 0x74, 0x36,
	0x34, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52,
	0x0a, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x21, 0x0a, 0x0b, 0x62,
	0x79, 0x74, 0x65, 0x73, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c,
	0x48, 0x00, 0x52, 0x0a, 0x62, 0x79, 0x74, 0x65, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x42, 0x0a,
	0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x67, 0x0a, 0x1b, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x61, 0x62, 0x6c, 0x65, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x7a, 0x6f, 0x6e, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x7a, 0x6f, 0x6e, 0x65, 0x49, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x52, 0x0a, 0x1c, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x61, 0x62, 0x6c,
	0x65, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x63, 0x72, 0x61, 0x73,
	0x74, 0x72, 0x75, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x61, 0x63, 0x72,
	0x61, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x22, 0x7b, 0x0a, 0x1b, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x61, 0x62, 0x6c, 0x65, 0x44, 0x65, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x7a, 0x6f, 0x6e, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x7a, 0x6f, 0x6e, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x68, 0x61, 0x73, 0x68, 0x22, 0x32, 0x0a, 0x1c, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x61, 0x62,
	0x6c, 0x65, 0x44, 0x65, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x6a, 0x0a, 0x1e, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x79, 0x6d, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x7a, 0x6f, 0x6e, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x7a, 0x6f, 0x6e, 0x65, 0x49, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x53, 0x0a, 0x1f, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x61, 0x62,
	0x6c, 0x65, 0x53, 0x79, 0x6d, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x1c, 0x0a, 0x09, 0x61,
	0x63, 0x72, 0x61, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09,
	0x61, 0x63, 0x72, 0x61, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x22, 0x7e, 0x0a, 0x1e, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x79, 0x6d, 0x44, 0x65, 0x63, 0x72, 0x79, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x7a, 0x6f, 0x6e, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x7a, 0x6f, 0x6e, 0x65, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x22, 0x35, 0x0a, 0x1f, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x79, 0x6d, 0x44, 0x65, 0x63, 0x72, 0x79, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x22, 0x5c, 0x0a, 0x10, 0x51, 0x75, 0x65, 0x72, 0x79, 0x48, 0x61, 0x73, 0x68, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x12, 0x17, 0x0a, 0x07, 0x7a, 0x6f, 0x6e, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x06, 0x7a, 0x6f, 0x6e, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x27,
	0x0a, 0x11, 0x51, 0x75, 0x65, 0x72, 0x79, 0x48, 0x61, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x22, 0x67, 0x0a, 0x11, 0x44, 0x65, 0x63, 0x72, 0x79,
	0x70, 0x74, 0x53, 0x79, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x7a, 0x6f, 0x6e,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x7a, 0x6f, 0x6e, 0x65,
	0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x63, 0x72, 0x61, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x61, 0x63, 0x72, 0x61, 0x62, 0x6c, 0x6f, 0x63, 0x6b,
	0x22, 0x28, 0x0a, 0x12, 0x44, 0x65, 0x63, 0x72, 0x79, 0x70, 0x74, 0x53, 0x79, 0x6d, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x5d, 0x0a, 0x11, 0x45, 0x6e,
	0x63, 0x72, 0x79, 0x70, 0x74, 0x53, 0x79, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07,
	0x7a, 0x6f, 0x6e, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x7a,
	0x6f, 0x6e, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x32, 0x0a, 0x12, 0x45, 0x6e, 0x63,
	0x72, 0x79, 0x70, 0x74, 0x53, 0x79, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x61, 0x63, 0x72, 0x61, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x09, 0x61, 0x63, 0x72, 0x61, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x32, 0x4a, 0x0a,
	0x06, 0x52, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x40, 0x0a, 0x07, 0x44, 0x65, 0x63, 0x72, 0x79,
	0x70, 0x74, 0x12, 0x18, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65,
	0x63, 0x72, 0x79, 0x70, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x63, 0x72, 0x79, 0x70, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x32, 0x4a, 0x0a, 0x06, 0x57, 0x72, 0x69,
	0x74, 0x65, 0x72, 0x12, 0x40, 0x0a, 0x07, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x12, 0x18,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f,
	0x61, 0x70, 0x69, 0x2e, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x32, 0x99, 0x01, 0x0a, 0x0b, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x69,
	0x7a, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x43, 0x0a, 0x08, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x69, 0x7a,
	0x65, 0x12, 0x19, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x69, 0x7a, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x0a, 0x44, 0x65,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x69, 0x7a, 0x65, 0x12, 0x19, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f,
	0x61, 0x70, 0x69, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x32, 0x56, 0x0a, 0x09, 0x52, 0x65, 0x61, 0x64, 0x65, 0x72, 0x53, 0x79, 0x6d, 0x12, 0x49,
	0x0a, 0x0a, 0x44, 0x65, 0x63, 0x72, 0x79, 0x70, 0x74, 0x53, 0x79, 0x6d, 0x12, 0x1b, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x63, 0x72, 0x79, 0x70, 0x74, 0x53,
	0x79, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x5f, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x63, 0x72, 0x79, 0x70, 0x74, 0x53, 0x79, 0x6d, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x32, 0x56, 0x0a, 0x09, 0x57, 0x72, 0x69,
	0x74, 0x65, 0x72, 0x53, 0x79, 0x6d, 0x12, 0x49, 0x0a, 0x0a, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70,
	0x74, 0x53, 0x79, 0x6d, 0x12, 0x1b, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x61, 0x70, 0x69, 0x2e,
	0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x53, 0x79, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1c, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x45, 0x6e, 0x63,
	0x72, 0x79, 0x70, 0x74, 0x53, 0x79, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x32, 0x90, 0x04, 0x0a, 0x14, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x61, 0x62, 0x6c, 0x65,
	0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x64, 0x0a, 0x11, 0x45, 0x6e,
	0x63, 0x72, 0x79, 0x70, 0x74, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x61, 0x62, 0x6c, 0x65, 0x12,
	0x25, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x61, 0x62, 0x6c, 0x65, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x61, 0x70,
	0x69, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x61, 0x62, 0x6c, 0x65, 0x45, 0x6e, 0x63, 0x72,
	0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x64, 0x0a, 0x11, 0x44, 0x65, 0x63, 0x72, 0x79, 0x70, 0x74, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x25, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x61, 0x70, 0x69,
	0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x61, 0x62, 0x6c, 0x65, 0x44, 0x65, 0x63, 0x72, 0x79,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x61, 0x62,
	0x6c, 0x65, 0x44, 0x65, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x6d, 0x0a, 0x14, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70,
	0x74, 0x53, 0x79, 0x6d, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x28,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x61, 0x62, 0x6c, 0x65, 0x53, 0x79, 0x6d, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f,
	0x61, 0x70, 0x69, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x79,
	0x6d, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x6d, 0x0a, 0x14, 0x44, 0x65, 0x63, 0x72, 0x79, 0x70, 0x74,
	0x53, 0x79, 0x6d, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x28, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x61,
	0x62, 0x6c, 0x65, 0x53, 0x79, 0x6d, 0x44, 0x65, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x61,
	0x70, 0x69, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x79, 0x6d,
	0x44, 0x65, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x4e, 0x0a, 0x11, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x48, 0x61, 0x73, 0x68, 0x12, 0x1a, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x5f, 0x61, 0x70, 0x69, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x48, 0x61, 0x73, 0x68, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x61, 0x70, 0x69,
	0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x48, 0x61, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x3a, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x63, 0x6f, 0x73, 0x73, 0x61, 0x63, 0x6b, 0x6c, 0x61, 0x62, 0x73, 0x2f, 0x61,
	0x63, 0x72, 0x61, 0x2f, 0x63, 0x6d, 0x64, 0x2f, 0x61, 0x63, 0x72, 0x61, 0x2d, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x61, 0x70, 0x69,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cmd_acra_translator_grpc_api_api_proto_rawDescOnce sync.Once
	file_cmd_acra_translator_grpc_api_api_proto_rawDescData = file_cmd_acra_translator_grpc_api_api_proto_rawDesc
)

func file_cmd_acra_translator_grpc_api_api_proto_rawDescGZIP() []byte {
	file_cmd_acra_translator_grpc_api_api_proto_rawDescOnce.Do(func() {
		file_cmd_acra_translator_grpc_api_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_cmd_acra_translator_grpc_api_api_proto_rawDescData)
	})
	return file_cmd_acra_translator_grpc_api_api_proto_rawDescData
}

var file_cmd_acra_translator_grpc_api_api_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_cmd_acra_translator_grpc_api_api_proto_goTypes = []interface{}{
	(*DecryptRequest)(nil),                  // 0: grpc_api.DecryptRequest
	(*DecryptResponse)(nil),                 // 1: grpc_api.DecryptResponse
	(*EncryptRequest)(nil),                  // 2: grpc_api.EncryptRequest
	(*EncryptResponse)(nil),                 // 3: grpc_api.EncryptResponse
	(*TokenizeRequest)(nil),                 // 4: grpc_api.TokenizeRequest
	(*TokenizeResponse)(nil),                // 5: grpc_api.TokenizeResponse
	(*SearchableEncryptionRequest)(nil),     // 6: grpc_api.SearchableEncryptionRequest
	(*SearchableEncryptionResponse)(nil),    // 7: grpc_api.SearchableEncryptionResponse
	(*SearchableDecryptionRequest)(nil),     // 8: grpc_api.SearchableDecryptionRequest
	(*SearchableDecryptionResponse)(nil),    // 9: grpc_api.SearchableDecryptionResponse
	(*SearchableSymEncryptionRequest)(nil),  // 10: grpc_api.SearchableSymEncryptionRequest
	(*SearchableSymEncryptionResponse)(nil), // 11: grpc_api.SearchableSymEncryptionResponse
	(*SearchableSymDecryptionRequest)(nil),  // 12: grpc_api.SearchableSymDecryptionRequest
	(*SearchableSymDecryptionResponse)(nil), // 13: grpc_api.SearchableSymDecryptionResponse
	(*QueryHashRequest)(nil),                // 14: grpc_api.QueryHashRequest
	(*QueryHashResponse)(nil),               // 15: grpc_api.QueryHashResponse
	(*DecryptSymRequest)(nil),               // 16: grpc_api.DecryptSymRequest
	(*DecryptSymResponse)(nil),              // 17: grpc_api.DecryptSymResponse
	(*EncryptSymRequest)(nil),               // 18: grpc_api.EncryptSymRequest
	(*EncryptSymResponse)(nil),              // 19: grpc_api.EncryptSymResponse
}
var file_cmd_acra_translator_grpc_api_api_proto_depIdxs = []int32{
	0,  // 0: grpc_api.Reader.Decrypt:input_type -> grpc_api.DecryptRequest
	2,  // 1: grpc_api.Writer.Encrypt:input_type -> grpc_api.EncryptRequest
	4,  // 2: grpc_api.Tokenizator.Tokenize:input_type -> grpc_api.TokenizeRequest
	4,  // 3: grpc_api.Tokenizator.Detokenize:input_type -> grpc_api.TokenizeRequest
	16, // 4: grpc_api.ReaderSym.DecryptSym:input_type -> grpc_api.DecryptSymRequest
	18, // 5: grpc_api.WriterSym.EncryptSym:input_type -> grpc_api.EncryptSymRequest
	6,  // 6: grpc_api.SearchableEncryption.EncryptSearchable:input_type -> grpc_api.SearchableEncryptionRequest
	8,  // 7: grpc_api.SearchableEncryption.DecryptSearchable:input_type -> grpc_api.SearchableDecryptionRequest
	10, // 8: grpc_api.SearchableEncryption.EncryptSymSearchable:input_type -> grpc_api.SearchableSymEncryptionRequest
	12, // 9: grpc_api.SearchableEncryption.DecryptSymSearchable:input_type -> grpc_api.SearchableSymDecryptionRequest
	14, // 10: grpc_api.SearchableEncryption.GenerateQueryHash:input_type -> grpc_api.QueryHashRequest
	1,  // 11: grpc_api.Reader.Decrypt:output_type -> grpc_api.DecryptResponse
	3,  // 12: grpc_api.Writer.Encrypt:output_type -> grpc_api.EncryptResponse
	5,  // 13: grpc_api.Tokenizator.Tokenize:output_type -> grpc_api.TokenizeResponse
	5,  // 14: grpc_api.Tokenizator.Detokenize:output_type -> grpc_api.TokenizeResponse
	17, // 15: grpc_api.ReaderSym.DecryptSym:output_type -> grpc_api.DecryptSymResponse
	19, // 16: grpc_api.WriterSym.EncryptSym:output_type -> grpc_api.EncryptSymResponse
	7,  // 17: grpc_api.SearchableEncryption.EncryptSearchable:output_type -> grpc_api.SearchableEncryptionResponse
	9,  // 18: grpc_api.SearchableEncryption.DecryptSearchable:output_type -> grpc_api.SearchableDecryptionResponse
	11, // 19: grpc_api.SearchableEncryption.EncryptSymSearchable:output_type -> grpc_api.SearchableSymEncryptionResponse
	13, // 20: grpc_api.SearchableEncryption.DecryptSymSearchable:output_type -> grpc_api.SearchableSymDecryptionResponse
	15, // 21: grpc_api.SearchableEncryption.GenerateQueryHash:output_type -> grpc_api.QueryHashResponse
	11, // [11:22] is the sub-list for method output_type
	0,  // [0:11] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_cmd_acra_translator_grpc_api_api_proto_init() }
func file_cmd_acra_translator_grpc_api_api_proto_init() {
	if File_cmd_acra_translator_grpc_api_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cmd_acra_translator_grpc_api_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DecryptRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_acra_translator_grpc_api_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DecryptResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_acra_translator_grpc_api_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EncryptRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_acra_translator_grpc_api_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EncryptResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_acra_translator_grpc_api_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TokenizeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_acra_translator_grpc_api_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TokenizeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_acra_translator_grpc_api_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchableEncryptionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_acra_translator_grpc_api_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchableEncryptionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_acra_translator_grpc_api_api_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchableDecryptionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_acra_translator_grpc_api_api_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchableDecryptionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_acra_translator_grpc_api_api_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchableSymEncryptionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_acra_translator_grpc_api_api_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchableSymEncryptionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_acra_translator_grpc_api_api_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchableSymDecryptionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_acra_translator_grpc_api_api_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchableSymDecryptionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_acra_translator_grpc_api_api_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryHashRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_acra_translator_grpc_api_api_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryHashResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_acra_translator_grpc_api_api_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DecryptSymRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_acra_translator_grpc_api_api_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DecryptSymResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_acra_translator_grpc_api_api_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EncryptSymRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_acra_translator_grpc_api_api_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EncryptSymResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_cmd_acra_translator_grpc_api_api_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*TokenizeRequest_StrValue)(nil),
		(*TokenizeRequest_EmailValue)(nil),
		(*TokenizeRequest_Int32Value)(nil),
		(*TokenizeRequest_Int64Value)(nil),
		(*TokenizeRequest_BytesValue)(nil),
	}
	file_cmd_acra_translator_grpc_api_api_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*TokenizeResponse_StrToken)(nil),
		(*TokenizeResponse_EmailToken)(nil),
		(*TokenizeResponse_Int32Token)(nil),
		(*TokenizeResponse_Int64Token)(nil),
		(*TokenizeResponse_BytesToken)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cmd_acra_translator_grpc_api_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   6,
		},
		GoTypes:           file_cmd_acra_translator_grpc_api_api_proto_goTypes,
		DependencyIndexes: file_cmd_acra_translator_grpc_api_api_proto_depIdxs,
		MessageInfos:      file_cmd_acra_translator_grpc_api_api_proto_msgTypes,
	}.Build()
	File_cmd_acra_translator_grpc_api_api_proto = out.File
	file_cmd_acra_translator_grpc_api_api_proto_rawDesc = nil
	file_cmd_acra_translator_grpc_api_api_proto_goTypes = nil
	file_cmd_acra_translator_grpc_api_api_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ReaderClient is the client API for Reader service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ReaderClient interface {
	Decrypt(ctx context.Context, in *DecryptRequest, opts ...grpc.CallOption) (*DecryptResponse, error)
}

type readerClient struct {
	cc grpc.ClientConnInterface
}

func NewReaderClient(cc grpc.ClientConnInterface) ReaderClient {
	return &readerClient{cc}
}

func (c *readerClient) Decrypt(ctx context.Context, in *DecryptRequest, opts ...grpc.CallOption) (*DecryptResponse, error) {
	out := new(DecryptResponse)
	err := c.cc.Invoke(ctx, "/grpc_api.Reader/Decrypt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReaderServer is the server API for Reader service.
type ReaderServer interface {
	Decrypt(context.Context, *DecryptRequest) (*DecryptResponse, error)
}

// UnimplementedReaderServer can be embedded to have forward compatible implementations.
type UnimplementedReaderServer struct {
}

func (*UnimplementedReaderServer) Decrypt(context.Context, *DecryptRequest) (*DecryptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Decrypt not implemented")
}

func RegisterReaderServer(s *grpc.Server, srv ReaderServer) {
	s.RegisterService(&_Reader_serviceDesc, srv)
}

func _Reader_Decrypt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecryptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReaderServer).Decrypt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_api.Reader/Decrypt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReaderServer).Decrypt(ctx, req.(*DecryptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Reader_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc_api.Reader",
	HandlerType: (*ReaderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Decrypt",
			Handler:    _Reader_Decrypt_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cmd/acra-translator/grpc_api/api.proto",
}

// WriterClient is the client API for Writer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WriterClient interface {
	Encrypt(ctx context.Context, in *EncryptRequest, opts ...grpc.CallOption) (*EncryptResponse, error)
}

type writerClient struct {
	cc grpc.ClientConnInterface
}

func NewWriterClient(cc grpc.ClientConnInterface) WriterClient {
	return &writerClient{cc}
}

func (c *writerClient) Encrypt(ctx context.Context, in *EncryptRequest, opts ...grpc.CallOption) (*EncryptResponse, error) {
	out := new(EncryptResponse)
	err := c.cc.Invoke(ctx, "/grpc_api.Writer/Encrypt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WriterServer is the server API for Writer service.
type WriterServer interface {
	Encrypt(context.Context, *EncryptRequest) (*EncryptResponse, error)
}

// UnimplementedWriterServer can be embedded to have forward compatible implementations.
type UnimplementedWriterServer struct {
}

func (*UnimplementedWriterServer) Encrypt(context.Context, *EncryptRequest) (*EncryptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Encrypt not implemented")
}

func RegisterWriterServer(s *grpc.Server, srv WriterServer) {
	s.RegisterService(&_Writer_serviceDesc, srv)
}

func _Writer_Encrypt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EncryptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WriterServer).Encrypt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_api.Writer/Encrypt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WriterServer).Encrypt(ctx, req.(*EncryptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Writer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc_api.Writer",
	HandlerType: (*WriterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Encrypt",
			Handler:    _Writer_Encrypt_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cmd/acra-translator/grpc_api/api.proto",
}

// TokenizatorClient is the client API for Tokenizator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TokenizatorClient interface {
	Tokenize(ctx context.Context, in *TokenizeRequest, opts ...grpc.CallOption) (*TokenizeResponse, error)
	Detokenize(ctx context.Context, in *TokenizeRequest, opts ...grpc.CallOption) (*TokenizeResponse, error)
}

type tokenizatorClient struct {
	cc grpc.ClientConnInterface
}

func NewTokenizatorClient(cc grpc.ClientConnInterface) TokenizatorClient {
	return &tokenizatorClient{cc}
}

func (c *tokenizatorClient) Tokenize(ctx context.Context, in *TokenizeRequest, opts ...grpc.CallOption) (*TokenizeResponse, error) {
	out := new(TokenizeResponse)
	err := c.cc.Invoke(ctx, "/grpc_api.Tokenizator/Tokenize", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenizatorClient) Detokenize(ctx context.Context, in *TokenizeRequest, opts ...grpc.CallOption) (*TokenizeResponse, error) {
	out := new(TokenizeResponse)
	err := c.cc.Invoke(ctx, "/grpc_api.Tokenizator/Detokenize", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TokenizatorServer is the server API for Tokenizator service.
type TokenizatorServer interface {
	Tokenize(context.Context, *TokenizeRequest) (*TokenizeResponse, error)
	Detokenize(context.Context, *TokenizeRequest) (*TokenizeResponse, error)
}

// UnimplementedTokenizatorServer can be embedded to have forward compatible implementations.
type UnimplementedTokenizatorServer struct {
}

func (*UnimplementedTokenizatorServer) Tokenize(context.Context, *TokenizeRequest) (*TokenizeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Tokenize not implemented")
}
func (*UnimplementedTokenizatorServer) Detokenize(context.Context, *TokenizeRequest) (*TokenizeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Detokenize not implemented")
}

func RegisterTokenizatorServer(s *grpc.Server, srv TokenizatorServer) {
	s.RegisterService(&_Tokenizator_serviceDesc, srv)
}

func _Tokenizator_Tokenize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenizatorServer).Tokenize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_api.Tokenizator/Tokenize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenizatorServer).Tokenize(ctx, req.(*TokenizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tokenizator_Detokenize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenizatorServer).Detokenize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_api.Tokenizator/Detokenize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenizatorServer).Detokenize(ctx, req.(*TokenizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Tokenizator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc_api.Tokenizator",
	HandlerType: (*TokenizatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Tokenize",
			Handler:    _Tokenizator_Tokenize_Handler,
		},
		{
			MethodName: "Detokenize",
			Handler:    _Tokenizator_Detokenize_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cmd/acra-translator/grpc_api/api.proto",
}

// ReaderSymClient is the client API for ReaderSym service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ReaderSymClient interface {
	DecryptSym(ctx context.Context, in *DecryptSymRequest, opts ...grpc.CallOption) (*DecryptSymResponse, error)
}

type readerSymClient struct {
	cc grpc.ClientConnInterface
}

func NewReaderSymClient(cc grpc.ClientConnInterface) ReaderSymClient {
	return &readerSymClient{cc}
}

func (c *readerSymClient) DecryptSym(ctx context.Context, in *DecryptSymRequest, opts ...grpc.CallOption) (*DecryptSymResponse, error) {
	out := new(DecryptSymResponse)
	err := c.cc.Invoke(ctx, "/grpc_api.ReaderSym/DecryptSym", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReaderSymServer is the server API for ReaderSym service.
type ReaderSymServer interface {
	DecryptSym(context.Context, *DecryptSymRequest) (*DecryptSymResponse, error)
}

// UnimplementedReaderSymServer can be embedded to have forward compatible implementations.
type UnimplementedReaderSymServer struct {
}

func (*UnimplementedReaderSymServer) DecryptSym(context.Context, *DecryptSymRequest) (*DecryptSymResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DecryptSym not implemented")
}

func RegisterReaderSymServer(s *grpc.Server, srv ReaderSymServer) {
	s.RegisterService(&_ReaderSym_serviceDesc, srv)
}

func _ReaderSym_DecryptSym_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecryptSymRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReaderSymServer).DecryptSym(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_api.ReaderSym/DecryptSym",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReaderSymServer).DecryptSym(ctx, req.(*DecryptSymRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ReaderSym_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc_api.ReaderSym",
	HandlerType: (*ReaderSymServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DecryptSym",
			Handler:    _ReaderSym_DecryptSym_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cmd/acra-translator/grpc_api/api.proto",
}

// WriterSymClient is the client API for WriterSym service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WriterSymClient interface {
	EncryptSym(ctx context.Context, in *EncryptSymRequest, opts ...grpc.CallOption) (*EncryptSymResponse, error)
}

type writerSymClient struct {
	cc grpc.ClientConnInterface
}

func NewWriterSymClient(cc grpc.ClientConnInterface) WriterSymClient {
	return &writerSymClient{cc}
}

func (c *writerSymClient) EncryptSym(ctx context.Context, in *EncryptSymRequest, opts ...grpc.CallOption) (*EncryptSymResponse, error) {
	out := new(EncryptSymResponse)
	err := c.cc.Invoke(ctx, "/grpc_api.WriterSym/EncryptSym", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WriterSymServer is the server API for WriterSym service.
type WriterSymServer interface {
	EncryptSym(context.Context, *EncryptSymRequest) (*EncryptSymResponse, error)
}

// UnimplementedWriterSymServer can be embedded to have forward compatible implementations.
type UnimplementedWriterSymServer struct {
}

func (*UnimplementedWriterSymServer) EncryptSym(context.Context, *EncryptSymRequest) (*EncryptSymResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EncryptSym not implemented")
}

func RegisterWriterSymServer(s *grpc.Server, srv WriterSymServer) {
	s.RegisterService(&_WriterSym_serviceDesc, srv)
}

func _WriterSym_EncryptSym_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EncryptSymRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WriterSymServer).EncryptSym(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_api.WriterSym/EncryptSym",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WriterSymServer).EncryptSym(ctx, req.(*EncryptSymRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WriterSym_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc_api.WriterSym",
	HandlerType: (*WriterSymServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EncryptSym",
			Handler:    _WriterSym_EncryptSym_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cmd/acra-translator/grpc_api/api.proto",
}

// SearchableEncryptionClient is the client API for SearchableEncryption service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SearchableEncryptionClient interface {
	EncryptSearchable(ctx context.Context, in *SearchableEncryptionRequest, opts ...grpc.CallOption) (*SearchableEncryptionResponse, error)
	DecryptSearchable(ctx context.Context, in *SearchableDecryptionRequest, opts ...grpc.CallOption) (*SearchableDecryptionResponse, error)
	EncryptSymSearchable(ctx context.Context, in *SearchableSymEncryptionRequest, opts ...grpc.CallOption) (*SearchableSymEncryptionResponse, error)
	DecryptSymSearchable(ctx context.Context, in *SearchableSymDecryptionRequest, opts ...grpc.CallOption) (*SearchableSymDecryptionResponse, error)
	GenerateQueryHash(ctx context.Context, in *QueryHashRequest, opts ...grpc.CallOption) (*QueryHashResponse, error)
}

type searchableEncryptionClient struct {
	cc grpc.ClientConnInterface
}

func NewSearchableEncryptionClient(cc grpc.ClientConnInterface) SearchableEncryptionClient {
	return &searchableEncryptionClient{cc}
}

func (c *searchableEncryptionClient) EncryptSearchable(ctx context.Context, in *SearchableEncryptionRequest, opts ...grpc.CallOption) (*SearchableEncryptionResponse, error) {
	out := new(SearchableEncryptionResponse)
	err := c.cc.Invoke(ctx, "/grpc_api.SearchableEncryption/EncryptSearchable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchableEncryptionClient) DecryptSearchable(ctx context.Context, in *SearchableDecryptionRequest, opts ...grpc.CallOption) (*SearchableDecryptionResponse, error) {
	out := new(SearchableDecryptionResponse)
	err := c.cc.Invoke(ctx, "/grpc_api.SearchableEncryption/DecryptSearchable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchableEncryptionClient) EncryptSymSearchable(ctx context.Context, in *SearchableSymEncryptionRequest, opts ...grpc.CallOption) (*SearchableSymEncryptionResponse, error) {
	out := new(SearchableSymEncryptionResponse)
	err := c.cc.Invoke(ctx, "/grpc_api.SearchableEncryption/EncryptSymSearchable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchableEncryptionClient) DecryptSymSearchable(ctx context.Context, in *SearchableSymDecryptionRequest, opts ...grpc.CallOption) (*SearchableSymDecryptionResponse, error) {
	out := new(SearchableSymDecryptionResponse)
	err := c.cc.Invoke(ctx, "/grpc_api.SearchableEncryption/DecryptSymSearchable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchableEncryptionClient) GenerateQueryHash(ctx context.Context, in *QueryHashRequest, opts ...grpc.CallOption) (*QueryHashResponse, error) {
	out := new(QueryHashResponse)
	err := c.cc.Invoke(ctx, "/grpc_api.SearchableEncryption/GenerateQueryHash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchableEncryptionServer is the server API for SearchableEncryption service.
type SearchableEncryptionServer interface {
	EncryptSearchable(context.Context, *SearchableEncryptionRequest) (*SearchableEncryptionResponse, error)
	DecryptSearchable(context.Context, *SearchableDecryptionRequest) (*SearchableDecryptionResponse, error)
	EncryptSymSearchable(context.Context, *SearchableSymEncryptionRequest) (*SearchableSymEncryptionResponse, error)
	DecryptSymSearchable(context.Context, *SearchableSymDecryptionRequest) (*SearchableSymDecryptionResponse, error)
	GenerateQueryHash(context.Context, *QueryHashRequest) (*QueryHashResponse, error)
}

// UnimplementedSearchableEncryptionServer can be embedded to have forward compatible implementations.
type UnimplementedSearchableEncryptionServer struct {
}

func (*UnimplementedSearchableEncryptionServer) EncryptSearchable(context.Context, *SearchableEncryptionRequest) (*SearchableEncryptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EncryptSearchable not implemented")
}
func (*UnimplementedSearchableEncryptionServer) DecryptSearchable(context.Context, *SearchableDecryptionRequest) (*SearchableDecryptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DecryptSearchable not implemented")
}
func (*UnimplementedSearchableEncryptionServer) EncryptSymSearchable(context.Context, *SearchableSymEncryptionRequest) (*SearchableSymEncryptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EncryptSymSearchable not implemented")
}
func (*UnimplementedSearchableEncryptionServer) DecryptSymSearchable(context.Context, *SearchableSymDecryptionRequest) (*SearchableSymDecryptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DecryptSymSearchable not implemented")
}
func (*UnimplementedSearchableEncryptionServer) GenerateQueryHash(context.Context, *QueryHashRequest) (*QueryHashResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateQueryHash not implemented")
}

func RegisterSearchableEncryptionServer(s *grpc.Server, srv SearchableEncryptionServer) {
	s.RegisterService(&_SearchableEncryption_serviceDesc, srv)
}

func _SearchableEncryption_EncryptSearchable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchableEncryptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchableEncryptionServer).EncryptSearchable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_api.SearchableEncryption/EncryptSearchable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchableEncryptionServer).EncryptSearchable(ctx, req.(*SearchableEncryptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchableEncryption_DecryptSearchable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchableDecryptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchableEncryptionServer).DecryptSearchable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_api.SearchableEncryption/DecryptSearchable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchableEncryptionServer).DecryptSearchable(ctx, req.(*SearchableDecryptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchableEncryption_EncryptSymSearchable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchableSymEncryptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchableEncryptionServer).EncryptSymSearchable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_api.SearchableEncryption/EncryptSymSearchable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchableEncryptionServer).EncryptSymSearchable(ctx, req.(*SearchableSymEncryptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchableEncryption_DecryptSymSearchable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchableSymDecryptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchableEncryptionServer).DecryptSymSearchable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_api.SearchableEncryption/DecryptSymSearchable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchableEncryptionServer).DecryptSymSearchable(ctx, req.(*SearchableSymDecryptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchableEncryption_GenerateQueryHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchableEncryptionServer).GenerateQueryHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_api.SearchableEncryption/GenerateQueryHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchableEncryptionServer).GenerateQueryHash(ctx, req.(*QueryHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SearchableEncryption_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc_api.SearchableEncryption",
	HandlerType: (*SearchableEncryptionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EncryptSearchable",
			Handler:    _SearchableEncryption_EncryptSearchable_Handler,
		},
		{
			MethodName: "DecryptSearchable",
			Handler:    _SearchableEncryption_DecryptSearchable_Handler,
		},
		{
			MethodName: "EncryptSymSearchable",
			Handler:    _SearchableEncryption_EncryptSymSearchable_Handler,
		},
		{
			MethodName: "DecryptSymSearchable",
			Handler:    _SearchableEncryption_DecryptSymSearchable_Handler,
		},
		{
			MethodName: "GenerateQueryHash",
			Handler:    _SearchableEncryption_GenerateQueryHash_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cmd/acra-translator/grpc_api/api.proto",
}
