source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
project 'AcraWriterSwift.xcodeproj'
inhibit_all_warnings!
use_frameworks!

target :"AcraWriterSwift" do
	pod 'acrawriter', '1.0.3'
end