// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: tokenTypes.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TokenType defines tokenization type.
type TokenType int32

const (
	TokenType_Unknown  TokenType = 0
	TokenType_Int32    TokenType = 1
	TokenType_Int64    TokenType = 2
	TokenType_String   TokenType = 3
	TokenType_Bytes    TokenType = 4
	TokenType_Email    TokenType = 5
	TokenType_Int32Str TokenType = 6
	TokenType_Int64Str TokenType = 7
)

// Enum value maps for TokenType.
var (
	TokenType_name = map[int32]string{
		0: "Unknown",
		1: "Int32",
		2: "Int64",
		3: "String",
		4: "Bytes",
		5: "Email",
		6: "Int32Str",
		7: "Int64Str",
	}
	TokenType_value = map[string]int32{
		"Unknown":  0,
		"Int32":    1,
		"Int64":    2,
		"String":   3,
		"Bytes":    4,
		"Email":    5,
		"Int32Str": 6,
		"Int64Str": 7,
	}
)

func (x TokenType) Enum() *TokenType {
	p := new(TokenType)
	*p = x
	return p
}

func (x TokenType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TokenType) Descriptor() protoreflect.EnumDescriptor {
	return file_tokenTypes_proto_enumTypes[0].Descriptor()
}

func (TokenType) Type() protoreflect.EnumType {
	return &file_tokenTypes_proto_enumTypes[0]
}

func (x TokenType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TokenType.Descriptor instead.
func (TokenType) EnumDescriptor() ([]byte, []int) {
	return file_tokenTypes_proto_rawDescGZIP(), []int{0}
}

// TokenValue keeps serialized token value.
type TokenValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []byte    `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Type  TokenType `protobuf:"varint,2,opt,name=type,proto3,enum=common.TokenType" json:"type,omitempty"`
}

func (x *TokenValue) Reset() {
	*x = TokenValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tokenTypes_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenValue) ProtoMessage() {}

func (x *TokenValue) ProtoReflect() protoreflect.Message {
	mi := &file_tokenTypes_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenValue.ProtoReflect.Descriptor instead.
func (*TokenValue) Descriptor() ([]byte, []int) {
	return file_tokenTypes_proto_rawDescGZIP(), []int{0}
}

func (x *TokenValue) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *TokenValue) GetType() TokenType {
	if x != nil {
		return x.Type
	}
	return TokenType_Unknown
}

var File_tokenTypes_proto protoreflect.FileDescriptor

var file_tokenTypes_proto_rawDesc = []byte{
	0x0a, 0x10, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x22, 0x49, 0x0a, 0x0a, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x25,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x2a, 0x6c, 0x0a, 0x09, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12,
	0x09, 0x0a, 0x05, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x49, 0x6e,
	0x74, 0x36, 0x34, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x10,
	0x03, 0x12, 0x09, 0x0a, 0x05, 0x42, 0x79, 0x74, 0x65, 0x73, 0x10, 0x04, 0x12, 0x09, 0x0a, 0x05,
	0x45, 0x6d, 0x61, 0x69, 0x6c, 0x10, 0x05, 0x12, 0x0c, 0x0a, 0x08, 0x49, 0x6e, 0x74, 0x33, 0x32,
	0x53, 0x74, 0x72, 0x10, 0x06, 0x12, 0x0c, 0x0a, 0x08, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x53, 0x74,
	0x72, 0x10, 0x07, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x63, 0x6f, 0x73, 0x73, 0x61, 0x63, 0x6b, 0x6c, 0x61, 0x62, 0x73, 0x2f, 0x61, 0x63,
	0x72, 0x61, 0x2f, 0x70, 0x73, 0x65, 0x75, 0x64, 0x6f, 0x6e, 0x79, 0x6d, 0x69, 0x7a, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_tokenTypes_proto_rawDescOnce sync.Once
	file_tokenTypes_proto_rawDescData = file_tokenTypes_proto_rawDesc
)

func file_tokenTypes_proto_rawDescGZIP() []byte {
	file_tokenTypes_proto_rawDescOnce.Do(func() {
		file_tokenTypes_proto_rawDescData = protoimpl.X.CompressGZIP(file_tokenTypes_proto_rawDescData)
	})
	return file_tokenTypes_proto_rawDescData
}

var file_tokenTypes_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tokenTypes_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tokenTypes_proto_goTypes = []interface{}{
	(TokenType)(0),     // 0: common.TokenType
	(*TokenValue)(nil), // 1: common.TokenValue
}
var file_tokenTypes_proto_depIdxs = []int32{
	0, // 0: common.TokenValue.type:type_name -> common.TokenType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tokenTypes_proto_init() }
func file_tokenTypes_proto_init() {
	if File_tokenTypes_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tokenTypes_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TokenValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tokenTypes_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tokenTypes_proto_goTypes,
		DependencyIndexes: file_tokenTypes_proto_depIdxs,
		EnumInfos:         file_tokenTypes_proto_enumTypes,
		MessageInfos:      file_tokenTypes_proto_msgTypes,
	}.Build()
	File_tokenTypes_proto = out.File
	file_tokenTypes_proto_rawDesc = nil
	file_tokenTypes_proto_goTypes = nil
	file_tokenTypes_proto_depIdxs = nil
}
